server:
  port: 9401

project:
  appcode: 320000000002
  #4A统一授权用户名
  username4A: admin
  #4A统一授权密码
  password4A: admin
  #4A单点登录SLB
  ssourl: http://47.100.173.115:9090/cas #http://47.100.173.115:10000
  #4A统一授权SLB
  authurl: http://47.100.173.115:9000 #http://47.100.173.115:11080
  #4A统一人员机构SLB
  orgurl: http://47.100.173.115:12080 #http://47.100.173.115:10000
  #当前应用service地址
  weburl: http://0.0.0.0
spring:
  profiles: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/fbos?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: mysql

  servlet:
    multipart:
      file-size-threshold: 0
      location: /Users/Shared/temp
      max-file-size: 30MB
      max-request-size: 30MB